dist: xenial
language: java
jdk: openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.cache/pip"
  - "$HOME/miniconda3"
branches:
  only:
  - master
  - development
  - "/^[vV]?\\d+\\.\\d+\\.\\d+$/"
before_install: unset _JAVA_OPTIONS
install:
- "$HOME/miniconda3/bin/conda --version || ./.install-reports-dependencies.sh"
before_script: if [ "$VAADIN_CHARTS_LICENSE_CODE" != "" ]; then echo "$VAADIN_CHARTS_LICENSE_CODE"
  > ~/.vaadin.charts.developer.license; fi;
script: mvn --quiet --activate-profiles !development-build,!release-build --settings
  .travis.settings.xml clean cobertura:cobertura package
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles development-build,!release-build --settings
    .travis.settings.xml deploy -DskipITs
  on:
    branch: development
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
- skip_cleanup: true
  provider: script
  script: mvn --quiet --activate-profiles !development-build,release-build --settings
    .travis.settings.xml deploy -DskipITs
  on:
    condition: '"$TRAVIS_EVENT_TYPE" = "push"'
    tags: true
after_deploy:
- echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc && source ~/.bashrc
  && conda activate qbic-docs-build
- mvn --quiet --activate-profiles !development-build,!release-build --settings .travis.settings.xml
  site
- ./.generate-reports.py $TRAVIS_BRANCH $TRAVIS_REPO_SLUG "[skip travis] Updated gh-pages"
  "This commit was performed from travis-ci.com using a personal access key" "Build
  ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this
  build found at $TRAVIS_JOB_WEB_URL"
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
    rooms:
    - secure: "***"
env:
  global:
  - secure: HNCsV2IVik4b9iLHUS4gq0YqN8/rT2j4Y3fouw4HdKC5tbzVRGBKg+wefSsmBow+UxHYESWJ0vbDRp42dkX0f8KryBOJnk4ruK7b/vhN7V0aBRtTjB4EKu9x1NzXtR+c8yle/fxW0pJdV+bXg7fXReEE28Xsc6GKhlyoRwOjI+dek/9Dz/5bNpBMwsNQavdwRxsgh8UPjn2GwIjYDQ0aqcMjYX1Yxa8L9RiuPbvBSgOiJZc6oRmJHQe1N6+Y3dWTaL31dQ+ezF26F+90EjmMHIWQwTCYi5rXCn9//SG4qz2GhUc/WroaZv0VHvqZqIhiR/zlLKEhkqAhCFGF3bvS/jSFfiuN5r7CP+SqcN2tUdV8xJluy5GLr1hrIJc2ofZhQ56pC4cgCkWpyM7daF1FkbJGMnaL1/nvfpHp1SGrnADi5wZnaUAs4rfBXV/car2a7lUv4yEqaypT2P/g0/rDT4Yi/dk3OE4RzKBxZfeOXB2lrrDgQRNXpg/o4RJn+nM9l4sP+NqnFrS2cY9FLL9c1CarBm6APIReuKgQLzAYVWHaDK5w4svBDDzmlJq5MEvFMb15peWr7YIjkcGXHcFXlucFuC9DVvqiNAeIoYj+gmEyC67+CbZfRizqfX5sdgNTl1ZMo7FgCMJgHhl4niYZjtGUxNnAL9iGhkdxo2FibeQ=
  - secure: XOSgo21JdhYCuC3CpZuySUJtgNCl8b9RSDzJ4PK1/vFzDd8v0lfr8yh0hKNSZM9/w+rfpLb5iOmqCsbLFqkkJTJPUOZOAbrHLXMWlHlZaKNxv1TfLhKli5ARkbeFGIOx4tuLJDXnI22Diujpj1fJ0M1t5dVW3AP2N7SIXx9uap/nfLiNP4FR5Yx1/69pKotegTvN/jdVj4wdx7OFWfIawy1ZCI/7cgTugQY3EVrOySNWcbKdm2jrl2VfmR6rH11IpSNoBizDGrfsVehwuuki2B8fSaM7s+8jKyHajXO8ExeJMMx6+UAhWMzxiT6P6+0nXsyVT6kOosZZrhOnh60J7rxt3KiC9iC/xCW5C/b17Ktk1czGFfT4VZfn+2/y+vDdTJZmWoVIw1ulqJwRJ69ix4SN5H1TFDpolu3qWwhwuuOY/nEJPQ9WhW5ynRARNCCYClV+IKvUZyC1Iv56O6aVyiw6Eor4wMv4AvnyMZmKh//sTyc5mClWtsON+P5thRQpzjMddVzDdY1cdIWRnYs8V/7BvIyRSOSO6phPOD7nRYTHmKyvjcPsNVtbRSjeweTxVziYZJwJWBysSDntZdwsl7M5E9epPodJ6PzFyl98Cng7gRkJxq6brQe80CyiYF3pQcFHKpf2fU9ZLrb8E+DtOiJm7vP3oALU+xFzJezRMWI=
  - secure: aKEaqp/9X9P7sw1Gd2UK2NoSBWGs/3oHnnfCi7NjLawA5xvZ7UAZWIng9gIS/d7Nyu6ZOs7ISSHdO8/p3y8CntEWlSH1cAH7rgYzZRxbqSqaVlELbYqLmejRMl9ychw85uKuGw+R0G4cQaPt4qgTrxlLtpWz2Kkg9kZZvvDyGqZFhx52e9f05qsgdxGMR3PK+ek75ZBLK39d73ydZiumi4Bl8SXqvhmLvGgRavx8U0Cg9P2vAttrK8RPFZyYHLPwWmgMhI6vaArHdRbTIPSbwTgwCZO8RAXfTAcsbVB25jb1OTRXsmID7tF9CuH7MUkrwPWLO17GNC+V+jpZg6FVYwF+Ju/HM1Onhhj+VFvT0Fd2baCE4zuTRpACf+60RY+XTUELzYwkSvd9F7nE66nSMEvmUGrKyb4CE5n37bbDzzlARFgTPHY3EZ0n0XeXgR/6dgoRAMOdWFUr3hhPkjGUF02fmcqR+y6c1Ynd6vkyQ1pEQ4K3BkQTCmhPg9cz9JhU7cA2zTehaDGU6CYMB0g4EPIRRwUxE5w9/qMEQlJODwL7PfNvrLooBie1rRASYpO0+5j7XGrlYE+om8NLXrkrNRjGGEQp63FJR41xSlyfhnyd7Rc5q0IzT3p3u9MfA87M/fldcZw46C6r55O0auZAyVfDvDCBsNAYzgfcScKXAgk=
  - secure: Mx6+A7fsS/ObluCi1rvjvcdjOK+kWb5lEB601f9dlP091QVhtw2/E0L7TdtKSp4gfbngVN5OK+gW9i1odFMA5Ee+f2GMxZQwLDfwlzp8XbmGHecw966oS9YVDSmPVB3txTN33w0kUcwbgm3jq9TrzMk8gHa5iNT9+GoSF8qO7z7PmMWpkYx7lYapVkSrks78a9HMIZBF3UFX9HbUV+lucrMlb3Qr7V/EUweHy3qxh0wmn12Tvfk/rtSPdzlBDuc6/1daA47GHYRJW6JnUmpNFK+Kg8akI5Dovy7UQ6zMfV4bmBS8L5QMVJL+GkjSfllle3cExq2Eciv+77+HMS6C6RAWfi6y65EHdtnNsGvqTv7mg46A8Gb1POtIYxhpsq0SYq/6Qd8lCfEXdrFeU4Sh0PW/xd6l1JHTIrw0bIHLGlIaQufhAqMz3DUIs5lpfwmd2WFvP5/bWBNip04wqOLJrOJXknLW6jNFo0IMLCmP9huwh1QulD+pAR9zt4LR/y/ql1J8II9+lgI5iIzTnSR0xeiMSkaETdENv4BN/jUuRh1MC9wwvThe/+Fo6ys4a0iVJ9fO8AZgJgcCTCJoM6zrgUKOfhgttqmlwqkYKeUCSccjEO4e49ne2h+rDYlMMOtOcYiCPPYWPsihpdXdTa0rEcuZG2cKGYD3oHgqK0WjsxY=
